.github/workflows
name: Scholarship Unit test CI
on: [push, pull_request]
jobs:
test:
runs-on: ubuntu-latest
steps:
-name: Checkout code
uses: actions(checkout @v3

-name: Set up Python
uses: actions/setup_python @v4
with:
  python_version:'3.10'

-name Install dependencies
run:|
  python -m pip install --upgrade pip
  pip install pycode stlye

-name: Lint Python files with Pycodestyle
run:|
  python -m unittest discover - v  